input {
  file {
    path => "/usr/share/logstash/input/train_cleaned.csv"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => plain { charset => "UTF-8" }
  }
}

filter {
  csv {
    separator => ","
    columns => ["text", "id", "metadata"]
    skip_header => "true"
  }

  mutate {
    strip => ["id", "text"]
    remove_field => ["metadata"]       # 直接移除 metadata 欄位
  }
}

output {
  elasticsearch {
    hosts => ["http://localhost:9200"]
    index => "csvdata"
    document_id => "%{id}"             # 用id當document的_id
    # user => "elastic"                  # 有認證時填入
    # password => "你的密碼"
  }
  stdout { codec => rubydebug }        # 測試時可用，正式可拿掉
}
