-- scripts/init.sql
CREATE TABLE IF NOT EXISTS fineweb_data (
    id UUID PRIMARY KEY,
    text TEXT NOT NULL,
    metadata JSONB NOT NULL
    ) PARTITION BY HASH (id);

CREATE TABLE IF NOT EXISTS fineweb_data_0 PARTITION OF fineweb_data
    FOR VALUES WITH (MODULUS 8, REMAINDER 0);

CREATE TABLE IF NOT EXISTS fineweb_data_1 PARTITION OF fineweb_data
    FOR VALUES WITH (MODULUS 8, REMAINDER 1);

CREATE TABLE IF NOT EXISTS fineweb_data_2 PARTITION OF fineweb_data
    FOR VALUES WITH (MODULUS 8, REMAINDER 2);

CREATE TABLE IF NOT EXISTS fineweb_data_3 PARTITION OF fineweb_data
    FOR VALUES WITH (MODULUS 8, REMAINDER 3);

CREATE TABLE IF NOT EXISTS fineweb_data_4 PARTITION OF fineweb_data
    FOR VALUES WITH (MODULUS 8, REMAINDER 4);

CREATE TABLE IF NOT EXISTS fineweb_data_5 PARTITION OF fineweb_data
    FOR VALUES WITH (MODULUS 8, REMAINDER 5);

CREATE TABLE IF NOT EXISTS fineweb_data_6 PARTITION OF fineweb_data
    FOR VALUES WITH (MODULUS 8, REMAINDER 6);

CREATE TABLE IF NOT EXISTS fineweb_data_7 PARTITION OF fineweb_data
    FOR VALUES WITH (MODULUS 8, REMAINDER 7);

